# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data.proto
"""Generated protocol buffer code."""

# This is a placeholder file that would normally be generated by protoc
# In a real deployment, run: protoc --python_out=. ../proto/sensor_data.proto

class SensorReading:
    """
    Placeholder for protobuf SensorReading message.
    This would normally be auto-generated by protoc.
    """
    
    def __init__(self):
        self.timestamp_us = 0
        self.co2_ppm = None
        self.temperature_c = None
        self.humidity_percent = None
        self.quality_flags = 0
        self._has_co2_ppm = False
        self._has_temperature_c = False
        self._has_humidity_percent = False
    
    def ParseFromString(self, data):
        """Parse protobuf data (placeholder implementation)."""
        # This is a simplified placeholder
        # Real implementation would parse binary protobuf data
        import struct
        if len(data) >= 8:
            self.timestamp_us = struct.unpack('>Q', data[:8])[0]
        pass
    
    def HasField(self, field_name):
        """Check if optional field is set."""
        if field_name == 'co2_ppm':
            return self._has_co2_ppm
        elif field_name == 'temperature_c':
            return self._has_temperature_c
        elif field_name == 'humidity_percent':
            return self._has_humidity_percent
        return False